import { z } from 'zod';

import { CommandContextSchema } from './metadata.js';

export const COMMAND_TYPES = [
  'CreateOutlineSession',
  'SendOutlineMessage',
  'PauseOutlineSession',
  'AbandonOutlineSession',
  'GenerateOutlineCandidate',
  'ConfirmOutlineCandidate',
  'CreateOutlineAdjustmentSession',
  'PublishOutlineRevision',
  'CloseCourse',
  'EvaluateAutomaticCourseClosure',
  'CommitCourseReview',
  'MarkCourseReviewFailed',
  'StartLesson',
  'SendLessonMessage',
  'PauseLessonSession',
  'ResumeLessonSession',
  'TakeOverLessonSession',
  'StopGeneration',
  'AbandonLesson',
  'RestoreAbandonedLesson',
  'StartSupplementarySession',
  'ArchiveSupplementarySession',
  'BeginLessonClosure',
  'CommitStageReview',
  'CommitFinalReview',
  'AbortLessonClosure',
  'FinalizeLesson',
  'RetryFinalReview',
  'ResumeClosingLesson',
  'RequestStageReview',
  'RequestCourseReview',
  'RetryCourseReview',
  'RecoverPendingClosures',
  'PreviewPlanFlow',
  'ConfirmPlanFlow',
  'AssignLesson',
  'ChangeSchedule',
  'CancelSchedule',
  'PausePlanFlow',
  'ResumePlanFlow',
  'ReplanFlow',
  'DeletePlanFlow',
  'AppendOutboxBatch',
  'AdvanceProjection',
  'RebuildReadModel',
  'ReconcileProjection',
  'GenerateWeeklyReport',
  'RetryWeeklyReport',
  'CaptureEvidenceCheckpoint',
  'ExtractEvidenceCandidates',
  'RetryEvidenceExtraction',
  'SupersedeEvidence',
  'RevalidateEvidenceSafety',
  'SubmitGenerationTask',
  'CancelGenerationTask',
  'ValidateProvider',
  'SwitchProvider',
  'ReconnectRuntime',
  'SyncFrontendVersion',
  'DiagnoseRuntime',
] as const;

export const CommandTypeSchema = z.enum(COMMAND_TYPES);

export const CommandEnvelopeSchema = z.strictObject({
  type: CommandTypeSchema,
  context: CommandContextSchema,
  payload: z.record(z.string(), z.unknown()),
});

export type CommandType = (typeof COMMAND_TYPES)[number];
export type CommandEnvelope = Readonly<z.infer<typeof CommandEnvelopeSchema>>;
